name: axon-bench

on:
  workflow_dispatch:
    inputs:
      jmeterJmx:
        type: choice
        description: Make a choice of jmx
        required: true
        options:
          - axon-nativeTransfer.jmx
      wsUrl:
        description: 'websocket url'
        required: false
        default: 'ws://34.216.103.183:8010'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run:
          mvn clean package --file pom.xml

      - name: Download jar file
        run: |
          wget https://github.com/sunchengzhu/eth-performance/releases/download/v1.0.0/ethStats.jar

      - name: Run ethStats.jar
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/sunchengzhu/eth-performance/actions/workflows/ethStats.yml/dispatches \
            -d '{"ref":"main", "inputs": {"jarArg": "'${{ github.event.inputs.wsUrl }}'"}'

      - name: jmeter run
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 5c79cf6182d23299a7b0272a1fa18ff3
        run: |
          update_gist() {
            cmd=$1
            JSON_DATA=$(printf '{"description": "Updated gist","files": {"commands.txt": {"content": "%s"}}}' "$cmd")
            curl -X PATCH -H "Authorization: token $GH_TOKEN" https://api.github.com/gists/$GIST_ID -d "${JSON_DATA}"
          }
          update_gist "tps"
          mvn jmeter:jmeter@configuration2 -DjmeterTest=${{ github.event.inputs.jmeterJmx }}
          update_gist "stopTps"
          sleep 5
          update_gist "successRate"
          sleep 5
          update_gist "printBlockNumber"