name: gw-tx

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        required: true
        options:
          - alphanet
          - testnet
          - axon
      jmeterJmx:
        type: choice
        description: Make a choice of jmx
        required: true
        options:
          - nativeTransfer.jmx
      gistId:
        description: 'Gist ID'
        required: false
        default: 'bd29348042f0f1f8998728895dea3e65'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Set rpcUrl, wsUrl, and gasPrice environment variables
        run: |
          case "${{ github.event.inputs.env }}" in
            "alphanet")
              echo "rpcUrl=https://godwoken-alphanet-v1.ckbapp.dev" >> $GITHUB_ENV
              echo "wsUrl=wss://gw-alphanet-v1.godwoken.cf/ws" >> $GITHUB_ENV
              echo "gasPrice=1" >> $GITHUB_ENV
              ;;
            "testnet")
              echo "rpcUrl=https://v1.testnet.godwoken.io/rpc" >> $GITHUB_ENV
              echo "wsUrl=wss://v1.testnet.godwoken.io/ws" >> $GITHUB_ENV
              echo "gasPrice=60000000000" >> $GITHUB_ENV
              ;;
            "axon")
              echo "rpcUrl=http://34.216.103.183:8000" >> $GITHUB_ENV
              echo "wsUrl=ws://34.216.103.183:8010" >> $GITHUB_ENV
              echo "gasPrice=8" >> $GITHUB_ENV
              ;;
            *)
              echo "Invalid environment specified."
              exit 1
              ;;
          esac

      - name: Build with Maven
        run: mvn clean package --file pom.xml -q

      - name: Start EthStats workflow
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/sunchengzhu/eth-performance/actions/workflows/ethStats.yml/dispatches \
            -d '{"ref":"main", "inputs": {"jarArg": "'${{ env.wsUrl }}'", "gistId": "'${{ github.event.inputs.gistId }}'"}'

      - name: jmeter run
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ github.event.inputs.gistId }}
          RPC_URL: ${{ env.rpcUrl }}
        run: |
          update_gist() {
            cmd=$1
            JSON_DATA=$(printf '{"description": "Updated gist","files": {"commands.txt": {"content": "%s"}}}' "$cmd")
            curl -X PATCH -H "Authorization: token $GH_TOKEN" https://api.github.com/gists/${{ github.event.inputs.gistId }} -d "${JSON_DATA}"
          }
          update_gist "tps"
          echo "rpcUrl: ${{ env.rpcUrl }}"
          echo "wsUrl: ${{ env.wsUrl }}"
          echo "gasPrice: ${{ env.gasPrice }}"
          mvn jmeter:jmeter@configuration2 -DjmeterTest=${{ github.event.inputs.jmeterJmx }} -DrpcUrl=${{ env.rpcUrl }} -DgasPrice=${{ env.gasPrice }}
          update_gist "stopTps"
          sleep 5
          update_gist "successRate"
